version: "3.9"
services:

  application:
    container_name: application
    build: 
      context: ./ 
      dockerfile: ./ 
    env_file: ./project_env.env 
    ports:
      - published: 8000 
      - target: 8000 
    networks:
      - go_store_network 
    depends_on:
      - mongo_database 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
      retries: 5 
      timeout: 10s 
      interval: 10s 

  mongo_database: 
    container_name: mongo_database 
    image: mongo:latest 
    environment:
      MONGO_INITD_DATABASE: emails_db 
      MONGO_INITD_USER: mongo_user 
      MONGO_INITD_PASSWORD: mongo_password 
    ports:
      - 27018:27018 
    networks:
      - go_store_network 
    healthcheck:
      test: ["mongod -"]
      retries: 5 
      timeout: 10s 
      interval: 10s 

networks:
  go_store_network:
    external: true 
    name: go_store_network 
    