version: "3.9"
services:

  nginx_server: 
    container_name: nginx_server 
    image: nginx:latest 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
    ports:
      - 8001:80 
    depends_on:
      - email_service_application 

  email_service_application:
    container_name: application
    build: ./
    env_file: ./project_env.env 
    ports:
      - 8000:8000 
    networks:
      - go_store_network 
    depends_on:
      - mongo_database 
      - test_mongo_database 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
      retries: 5 
      timeout: 10s 
      interval: 10s 

  mongo_database: 
    container_name: mongo_database 
    image: mongo:latest 
    environment:
      MONGO_INITD_DATABASE: emails_db 
      MONGO_INITD_USERNAME: mongo_user 
      MONGO_INITD_PASSWORD: mongo_password 
    volumes:
      - ./mongo/docker-entrypoint-init.d/:/etc/mongod/docker-entrypoint-init.d/
      - ./mongo/db/data:/etc/mongod/db/data
    ports:
      - 27018:27018 
      - 29018:29018
    networks:
      - go_store_network 
    healthcheck:
      test: echo `db.runCommand("ping"),ok` | mongo mongo_database:27018/emails_db --quiet
      retries: 5 
      timeout: 10s 
      interval: 10s
      start_period: 30s 
      
  test_mongo_database:
    container_name: test_mongo_database 
    image: mongo:latest 
    environment:
      MONGO_INITD_DATABASE: emails_test_db 
      MONGO_INITD_USERNAME: mongo_user 
      MONGO_INITD_PASSWORD: mongo_password 
    ports:
      - 27017:27017 
      - 29017:29017 
    volumes:
      - ./mongo/docker-entrypoint-init.d/:/etc/mongod/docker-entrypoint-init.d/
      - ./mongo/db/data:/etc/mongod/db/data 
    networks:
      - go_store_network 
    healthcheck:
      test: echo `db.runCommand("ping"),ok` | mongo mongo_database:27018/emails_db --quiet
      retries: 5 
      timeout: 10s 
      interval: 10s 
      
networks:
  go_store_network:
    external: true 
    name: go_store_network 
    