version: "3.9"
services:

  email_nginx_server: 
    container_name: email_nginx_server 
    image: nginx:latest 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
    ports:
      - 8001:80 
    depends_on:
      - email_service_application 
    networks:
      - go_store_network 

  email_service_application:
    container_name: application
    build: ./
    env_file: ./project_env.env 
    ports:
      - 8000:8000 
    networks:
      - go_store_network 
    depends_on:
      - mongo_database 
      - test_mongo_database 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
      retries: 5 
      timeout: 10s 
      interval: 10s 

  mongo_database:
    container_name: mongodb_server 
    image: mongo:latest 
    environment:
      MONGO_INITDB_DATABASE: emails_db 
      MONGO_INITDB_ROOT_USERNAME: mongo_user 
      MONGO_INITDB_ROOT_PASSWORD: mongo_password 
    volumes:
      - ./mongo/docker-entrypoint-init.d/:/docker-entrypoint-initdb.d/ 
      - ./mongo/db/data:/data/db
    command: mongod --port 27017
    ports: 
      - 27017:27017
      - 29018:27018
    networks:
      - go_store_network 

    healthcheck:
      test: echo `db.runCommand("ping"),ok` | mongo mongo_database:27017/emails_db --quiet
      retries: 5 
      timeout: 10s 
      interval: 10s
      start_period: 30s 
      
networks:
  go_store_network:
    external: true 
    name: go_store_network 
    
volumes:
  mongo_data: 
    external: true 
  