apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: email-application-service 
  namespace: email-namespace 

spec:
    selector:
      matchLabels:
        run: internal-service 
    template:
      metadata: 
        labels:
          run: internal-service
      spec:
        containers:
        - name: email-service-application 
          image: crazycoderrr/email_service # this image should be installed
          ports:
          - containerPort: 8000 
            hostPort: 8000 
            protocol: TCP 
          
          envFrom:
            - secretRef:
                name: project-secrets

          imagePullPolicy: IfNotPresent

