apiVersion: v1 
kind: Service
metadata:
  name: email-internal-service 
  namespace: ingress-nginx 
spec:
  type: ClusterIP
  selector:
    run: internal-service
  ports:
   - name: http 
     port: 8060
     targetPort: 8060 
     protocol: TCP 

--- 

apiVersion: v1 
kind: Deployment 
metadata:
  name: email-application-service 
  namespace: email-namespace 

spec:
    selector:
      matchLabels:
        run: internal-service 
    template:
      metadata: 
        labels:
          run: internal-service
      spec:
        containers:
        - name: email-service-application 
          image: crazycoderrr/email_service # this image should be installed
          ports:
          - containerPort: 8060
            hostPort: 8060
            protocol: TCP 
          
          envFrom:
            - secretRef:
                name: project-secrets

          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command: curl -X GET -f http://localhost:8060/healthcheck/ 
              initialDelaySeconds: 10 

---

apiVersion: v1 
kind: Secret
metadata:
  name: project-secrets
  namespace: email-namespace 

type: Opaque 
stringData:

  MONGO_DATABASE_HOST: "mongo_database" 
  MONGO_DATABASE_PORT: "27017" 
  MONGO_DATABASE_USER: "mongo_emails_user" 
  MONGO_DATABASE_PASSWORD: "mongo_emails_password" 

  APPLICATION_HOST: "email_service_application" 
  APPLICATION_PORT: "8000"

  SMTP_SERVER_HOST: "smtp.gmail.com" 
  SMTP_SERVER_EMAIL: "email@gmail.com" 
  SMTP_SERVER_PASSWORD: "emailPassword" 
  SMTP_SERVER_PORT: "587" 

  GRPC_SERVER_HOST: "localhost" 
  GRPC_SERVER_PORT: "50000" 

  NGINX_PROXY_HOST: "nginx_server" 
  NGINX_PROXY_PORT: "80" 


