apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: email-application-service 
  labels:
    app: email-application-service  

  spec:
    replicas: 3 
    selector:
      matchLabels:
        app: email-application-service 
    template:
      metadata: 
        labels:
          app: email-application-service 
      spec:
        containers:
        - name: email-service-application 
          image: crazycoderrr/emails_service # this image should be installed
          ports:
          - containerPort: 8000 
          envFrom:
            - secretRef:
              name: ProjectSecrets
          restartPolicy: onFailure 
        
          livenessProbe:
            - httpGet:
              path: /healthcheck/
              port: 8000 
              protocol: HTTP  

          resources:
            requests:
              cpu: "0.5"
              memory: "3Gi"
            limits:
              cpu: "0.6"
              memory: "3Gi"
          
          hostNetwork: true 
          dnsPolicy: Default 



