apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: email-application-service 
  namespace: email-namespace 

spec:
    selector:
      matchLabels:
        app: internal-service 
    template:
      metadata: 
        labels:
          app: internal-service
      spec:
        containers:
        - name: email-service-application 
          image: crazycoderrr/email_service # this image should be installed
          ports:
          - containerPort: 8000 
          envFrom:
            - secretRef:
                name: project-secrets

          imagePullPolicy: Never
        
          livenessProbe:
            httpGet:
              path: /healthcheck/
              port: 8000 

          resources:
            requests:
              cpu: "0.5"
              memory: "3Gi"
            limits:
              cpu: "0.6"
              memory: "3Gi"
          
        hostNetwork: true 
        dnsPolicy: Default 

