apiVersion: v1 
kind: Service
metadata:
  name: email-internal-service 
  namespace: email-namespace 
spec:
  type: ClusterIP
  externalIPs:
    - 192.168.0.10 
  selector:
    run: internal-service
  ports:
   - name: http 
     port: 8000
     targetPort: 8000 
     protocol: TCP 



