apiVersion: v1 
kind: Service 
metadata:
  name: email-internal-service 
  namespace: email-namespace 
spec:
  type: ClusterIP 
  externalIPs:
    - 192.168.0.10 
  selector:
    app: internal-service
  ports:
   - name: http 
     port: 8000 # external port of the nginx deployment...
     targetPort: 8000 
     protocol: TCP 






