apiVersion: v1 
kind: Service
metadata:
  name: email-internal-service 
  namespace: ingress-nginx 
spec:
  type: ClusterIP
  selector:
    run: internal-service
  ports:
   - name: http 
     port: 8000
     targetPort: 8000 
     protocol: TCP 



