apiVersion: v1 
kind: PersistentVolume 
metadata:
  name: jenkins-volume 
  namespace: jenkins-server-namespace 
spec:
  StorageClassName: Jenkins-Storage 
  capacity:
    maxSize: "10Gi"
  requests:
    cpu: "0.5"
    memory: "2Gi"
  limits:
    cpu: "0.5"
    memory: "2Gi"

--- 

apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:
  name: jenkins-volume-claim 
  namespace: jenkins-server-namespace 
spec:
  StorageClassName: Jenkins-Storage 
  resources:
    requests:
      cpu: "0.5"
      memory: "2Gi"
    limits:
      cpu: "0.5"
      memory: "2Gi"

--- 

apiVersion: v1 
kind: Service 
metadata:
  name: jenkins-server-service
  namespace: ingress-nginx
spec: 
  type: ClusterIP
  ports: 
    - name: jenkins-server-ui
      containerPort: 8080
      targetPort: 8080

    - name: jenkins-server-management
      containerPort: 50000 
      targetPort: 50000 

--- 

apiVersion: v1 
kind: Deployment

metadata:
  name: jenkins-server 
  namespace: jenkins-server-namespace 

spec:
  template:
    metadata:
      labels: 
        app: jenkins-app 
    spec:
      containers:
        - name: jenkins-server 
          image: jenkins:lts 
          ports:
            - name: httpport 
              containerPort: 8080 
              targetPort: 8080 
            
            - name: jnlport 
              containerPort: 40000 
              targetPort: 40000

          livenessProbe:
            exec:
              command: 
            initialDelaySeconds: 10 

          VolumeMounts:
            - MountPath: /jenkins/home/ 
              name: jenkins-storage 
            - MountPath: /var/run/docker.sock 
              name: docker-socket-volume 

      Volumes:
        - name: jenkins-storage 
          PersistentClaim:
            claimName: jenkins-volume-claim 
        - name: docker-socket-volume 
          value: /var/run/docker.sock 



