apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: mongo-database-server
  labels:
    app: mongo-database-server 
  
spec:

  replicas: 3 
  selector:
    matchLabels:
      app: mongo-database-server 

  template:
    metadata: 
      labels:
        app: mongo-database-server 

    spec:
      restartPolicy: onFailure 
      dnsPolicy: Default 
      hostNetwork: true

      containers:

        - name: mongo-emails-service-database 
          image: mongo:latest 
          volumeMounts:

            - mountPath: docker-entrypoint-initdb.d/ 
              name: MongoConfiguration
              readOnly: true 

            - mountPath: /data/db
              name: MongoDataVolume 

          env:
            - name: MONGO_INITDB_DATABASE 
              valueFrom:
                  configMapKeyRef:
                    name: mongo-config-map
                    key: MONGO_DATABASE

            - name: MONGO_INITDB_ROOT_USER 
              valueFrom:
                configMapKeyRef:
                  name: mongo-config-map
                  key: MONGO_DATABASE_USER

            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mongo-config-map
                  key: MONGO_DATABASE_PASSWORD 
          ports:
            - containerPort: 27017 
            
          command: ["-mongod", "--port", "27017"] 
          resources:
          
              requests:
                 memory: "3Gi"
                 cpu: "0.5"
              limits:
                 memory: "3Gi"
                 cpu: "0.6"
              
        volumes:
         - name: MongoConfiguration
            hostPath:
              path: EmailService/mongo/docker-entrypoint-init.d/

        - name: MongoDataVolume 
            hostPath:
              path: EmailService/mongo/data/db






