apiVersion: v1 
kind: deployment 
metadata:
  name: mongo_database
  labels:
    app: mongo_database 
  
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: mongo_database 
    template:
      metadata: 
        labels:
          app: mongo_database 
      spec:
        containers:
          - name: mongo_emails_service_database 
          image: mongo:latest 
          volumeMounts:
            - MountPath: docker-entrypoint-initdb.d/ 
            - name: MongoConfiguration
            - readOnly: true 
          env:
            - name: MONGO_INITDB_DATABASE 
              value: emails_db 
            - name: MONGO_INITDB_ROOT_USER 
              value: mongo_user 
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mongo_password 
          ports:
            - protocol: TCP 
            - targetPort: 27017 
            - port: 27017 
          command: ["-mongod", "--port", "27017"] 
          restartPolicy: onFailure

          resources:
            requests:
              memory: "3Gi"
              cpu: "0.5"
            limits:
              memory: "3Gi"
              cpu: "0.6"

          livenessProbe:
            httpGet:  
              path: actuator/health/liveness 
            initialDelaySeconds: 20
            periodSeconds: 15 

        volumes:
          - name: MongoConfiguration
            hostPath:
              path: ./docker-entrypoint-init.d/





