apiVersion: v1 
kind: Secret
metadata:
  name: project-secrets
  namespace: email-namespace 

type: Opaque 
stringData:

  MONGO_DATABASE_HOST: "mongo_database" 
  MONGO_DATABASE_PORT: "27017" 
  MONGO_DATABASE_USER: "mongo_emails_user" 
  MONGO_DATABASE_PASSWORD: "mongo_emails_password" 

  APPLICATION_HOST: "email_service_application" 
  APPLICATION_PORT: "8000"

  SMTP_SERVER_HOST: "smtp.gmail.com" 
  SMTP_SERVER_EMAIL: "email@gmail.com" 
  SMTP_SERVER_PASSWORD: "emailPassword" 
  SMTP_SERVER_PORT: "587" 

  GRPC_SERVER_HOST: "localhost" 
  GRPC_SERVER_PORT: "50000" 

  NGINX_PROXY_HOST: "nginx_server" 
  NGINX_PROXY_PORT: "80" 



