version: "3.9"
services:
  
  mongodb_server:
    container_name: mongodb_server 
    image: mongo:latest 
    environment:
      MONGO_INITDB_DATABASE: emails_db 
      MONGO_INITDB_ROOT_USERNAME: mongo_user 
      MONGO_INITDB_ROOT_PASSWORD: mongo_password 
    volumes:
      - ./docker-entrypoint-init.d/:/docker-entrypoint-initdb.d/ 
      - ./db/data:/data/db
    command: mongod --port 27017
    ports: 
      - 27017:27017
      - 29018:27018


