version: "3.9"

services:
  
  mongodb_server:
    container_name: mongodb_server 
    image: mongo:latest 
    environment:
      MONGO_INITD_DATABASE: mongo_database 
      MONGO_INITD_USER: mongo_user 
      MONGO_INITD_PASSWORD: mongo_password 
    volumes:
      - ./docker-entrypoint-init.d/mongo.sh:/etc/docker-entrypoint.sh/ 
    ports: 
      - 27018:27018 
      - 29018:27018
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:8000"]
      retries: 5 
      timeout: 10s 
      interval: 10s 
